version: '3'
services:
  nginx-ftp:
    image: "sparkpos/vsftpd-nginx"
    container_name: nginx-ftp
    ports:
      - "20:20"
      - "21:21"
      - "8080:80"
      - "30000-30009:30000-30009"
    volumes:
      - "../../vsftp_data:/home/vsftpd"
      - "../../ui_dist:/usr/share/nginx/html:ro"
      - "../../ui_nginx_config:/etc/nginx/conf.d:ro"
    environment:
      - FTP_USER=ftpuser
      - FTP_PASS=passwd
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=30000
      - PASV_MAX_PORT=30009
      - FILE_OPEN_MODE=0777
      - LOCAL_UMASK=011
    restart: always
